include:
- project: 'mautrix/ci'
  file: '/go.yml'

# Don't use the default macOS job in mautrix/ci
build macos arm64:
  rules:
    - when: never

# TODO use build universal for all bridges? (i.e. move it to mautrix/ci)
build universal:
  stage: build
  tags:
  - macos
  - arm64
  variables:
    MACOSX_DEPLOYMENT_TARGET: "11.0"
  before_script:
  - export PATH=/opt/homebrew/bin:$PATH
  - export MAUTRIX_VERSION=$(cat go.mod | grep 'maunium.net/go/mautrix ' | awk '{ print $2 }')
  - export GO_LDFLAGS="-X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`' -X 'maunium.net/go/mautrix.GoModVersion=$MAUTRIX_VERSION'"
  - export CPATH=$(brew --prefix)/include
  script:
  # Build arm64 binary
  - MACOSX_DEPLOYMENT_TARGET=11.0 LIBRARY_PATH=/opt/homebrew/lib go build -ldflags "$GO_LDFLAGS" -o $BINARY_NAME-arm64
  - install_name_tool -change /opt/homebrew/opt/libolm/lib/libolm.3.dylib @rpath/libolm.3.dylib $BINARY_NAME-arm64
  - install_name_tool -add_rpath @executable_path $BINARY_NAME-arm64
  - install_name_tool -add_rpath /opt/homebrew/opt/libolm/lib $BINARY_NAME-arm64
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib $BINARY_NAME-arm64
  - install_name_tool -add_rpath /usr/local/lib $BINARY_NAME-arm64
  # Build amd64 binary
  - MACOSX_DEPLOYMENT_TARGET=10.13 LIBRARY_PATH=/usr/local/lib CGO_ENABLED=1 GOARCH=amd64 go build -ldflags "$GO_LDFLAGS" -o $BINARY_NAME-amd64
  - install_name_tool -change /usr/local/lib/libolm.3.dylib @rpath/libolm.3.dylib $BINARY_NAME-amd64
  - install_name_tool -add_rpath @executable_path $BINARY_NAME-amd64
  - install_name_tool -add_rpath /usr/local/opt/libolm/lib $BINARY_NAME-amd64
  - install_name_tool -add_rpath /usr/local/lib $BINARY_NAME-amd64
  # Create universal libolm and bridge binary
  - lipo -create -output libolm.3.dylib /opt/homebrew/opt/libolm/lib/libolm.3.dylib /usr/local/lib/libolm.3.dylib
  - lipo -create -output $BINARY_NAME $BINARY_NAME-arm64 $BINARY_NAME-amd64
  artifacts:
    paths:
    - $BINARY_NAME
    - example-config.yaml
    - libolm.3.dylib
